configpath: /home/al1-ce/.config/nom/config.yml
showfavourites: false
version: ""
feeds:
    - url: https://www.tecmint.com/feed/
      name: TecMint
    - url: https://archlinux.org/feeds/news/
      name: ArchLinux
ordering: asc
theme:
    glamour: dark
    titleColor: "62"
    filterColor: "62"
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2
